version: 2

models:
  - name: fact_tv_ratings
    description: ""
    columns:
      - name: movie_id
        data_type: string
        description: ""

      - name: average_rating
        data_type: float64
        description: ""

      - name: num_votes
        data_type: int64
        description: ""

      - name: runtime_minutes
        data_type: int64
        description: ""

  - name: fact_movie_ratings
    description: ""
    columns:
      - name: movie_id
        data_type: string
        description: ""

      - name: average_rating
        data_type: float64
        description: ""

      - name: num_votes
        data_type: int64
        description: ""

      - name: runtime_minutes
        data_type: int64
        description: ""

  - name: dim_writers
    description: ""
    columns:
      - name: writer_id
        data_type: string
        description: ""

      - name: writer_name
        data_type: string
        description: ""

      - name: birth_year
        data_type: int64
        description: ""

      - name: death_year
        data_type: int64
        description: ""

      - name: primary_professions
        data_type: string
        description: ""

  - name: dim_genres
    description: ""
    columns:
      - name: genre_id
        data_type: int64
        description: ""

      - name: genre_name
        data_type: string
        description: ""

  - name: dim_directors
    description: ""
    columns:
      - name: director_id
        data_type: string
        description: ""

      - name: director_name
        data_type: string
        description: ""

      - name: birth_year
        data_type: int64
        description: ""

      - name: death_year
        data_type: int64
        description: ""

      - name: primary_professions
        data_type: string
        description: ""

  - name: dim_actors
    description: ""
    columns:
      - name: name_id
        data_type: string
        description: ""

      - name: primary_name
        data_type: string
        description: ""

      - name: birth_year
        data_type: int64
        description: ""

      - name: death_year
        data_type: int64
        description: ""

      - name: primary_profession
        data_type: string
        description: ""
        
  - name: bridge_title_actors
    description: ""
    columns:
      - name: title_id
        data_type: string
        description: ""

      - name: name_id
        data_type: string
        description: ""

      - name: character_name
        data_type: string
        description: ""

  - name: bridge_title_directors
    description: ""
    columns:
      - name: title_id
        data_type: string
        description: ""

      - name: director_id
        data_type: string
        description: ""

  - name: bridge_title_writers
    description: ""
    columns:
      - name: title_id
        data_type: string
        description: ""

      - name: writer_id
        data_type: string
        description: ""

  - name: bridge_title_genres
    description: ""
    columns:
      - name: title_id
        data_type: string
        description: ""

      - name: genre_id
        data_type: int64
        description: ""
